[package]
name = "game-focus-scanner"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Aron Gustafson"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.5"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_System_Registry",
] }
